---
application:
  name: "teabot-api"
  project: "teabot"
  organization: "QoveryCommunity"
  storage:
  - name: "data"
    size: 5GB
    type: ssd
    mount_point: /mnt/data
databases:
- name: "my-redis"
  type: redis
  version: 6
routers:
- name: "main-teabot-api"
  routes:
  - application_name: "teabot-api"
    paths:
    - "/"
